version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8888:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=praemiepro
      - POSTGRES_USER=pp_dbuser
      - POSTGRES_PASSWORD=g4ANId3CSb0oQw81Lwm7
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=praemiepro
      - POSTGRES_USER=pp_dbuser
      - POSTGRES_PASSWORD=g4ANId3CSb0oQw81Lwm7
    ports:
      - "127.0.0.1:5434:5432"
    volumes:
      - ~/volumes/praemiepro:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pp_dbuser -d praemiepro" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
